name: governed_analytics_platform
version: 1.0.0
config-version: 2

profile: governed_analytics_platform

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  standardized_olist_path: "../data/standardized/olist"

models:
  governed_analytics_platform:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      core:
        +materialized: table
      published:
        +materialized: table
