select
    order_id,
    cast(order_item_id as integer) as order_item_id,
    customer_unique_id,
    order_status,
    cast(order_purchase_timestamp as timestamp) as order_purchase_timestamp,
    cast(order_delivered_customer_date as timestamp) as order_delivered_customer_date,
    cast(order_estimated_delivery_date as timestamp) as order_estimated_delivery_date,
    cast(order_date as date) as order_date,
    cast(order_year as integer) as order_year,
    cast(order_month as integer) as order_month,
    purchase_cohort_month,
    cast(cohort_order_month_number as integer) as cohort_order_month_number,
    cast(customer_order_sequence as integer) as customer_order_sequence,
    cast(is_first_order as boolean) as is_first_order,
    seller_key,
    seller_volume_tier,
    cast(seller_order_count as integer) as seller_order_count,
    cast(seller_avg_delivery_days as double) as seller_avg_delivery_days,
    cast(seller_delay_rate as double) as seller_delay_rate,
    cast(delivery_time_days as double) as delivery_time_days,
    cast(seller_dispatch_time_days as double) as seller_dispatch_time_days,
    cast(carrier_delivery_time_days as double) as carrier_delivery_time_days,
    cast(estimated_delay_days as double) as estimated_delay_days,
    cast(is_delayed as boolean) as is_delayed,
    cast(price as double) as price,
    cast(freight_value as double) as freight_value,
    cast(freight_to_price_ratio as double) as freight_to_price_ratio,
    cast(total_item_value as double) as total_item_value,
    payment_type_mode,
    cast(review_score_mean as double) as review_score_mean,
    product_category_name,
    product_category_name_english,
    customer_state,
    seller_state
from read_parquet('{{ var("published_dashboard_path") }}/fact_orders_dashboard.parquet')
