select
    order_id,
    order_item_id,
    customer_id,
    customer_unique_id,
    product_id,
    seller_id,
    order_status,
    cast(order_purchase_timestamp as timestamp) as order_purchase_timestamp,
    cast(order_approved_at as timestamp) as order_approved_at,
    cast(shipping_limit_date as timestamp) as shipping_limit_date,
    cast(order_delivered_carrier_date as timestamp) as order_delivered_carrier_date,
    cast(order_delivered_customer_date as timestamp) as order_delivered_customer_date,
    cast(order_estimated_delivery_date as timestamp) as order_estimated_delivery_date,
    cast(order_date as date) as order_date,
    cast(order_year as integer) as order_year,
    cast(order_month as integer) as order_month,
    purchase_cohort_month,
    cast(customer_first_purchase_timestamp as timestamp) as customer_first_purchase_timestamp,
    cast(cohort_order_month_number as integer) as cohort_order_month_number,
    cast(customer_order_sequence as integer) as customer_order_sequence,
    cast(is_first_order as boolean) as is_first_order,
    cast(delivery_time_days as double) as delivery_time_days,
    cast(seller_dispatch_time_days as double) as seller_dispatch_time_days,
    cast(carrier_delivery_time_days as double) as carrier_delivery_time_days,
    cast(estimated_delay_days as double) as estimated_delay_days,
    cast(is_delayed as boolean) as is_delayed,
    cast(price as double) as price,
    cast(freight_value as double) as freight_value,
    cast(freight_to_price_ratio as double) as freight_to_price_ratio,
    cast(total_item_value as double) as total_item_value,
    cast(payment_count as integer) as payment_count,
    cast(total_payment_value as double) as total_payment_value,
    cast(max_payment_installments as integer) as max_payment_installments,
    payment_type_mode,
    cast(review_count as integer) as review_count,
    cast(review_score_mean as double) as review_score_mean,
    cast(review_score_max as double) as review_score_max,
    cast(review_score_min as double) as review_score_min,
    cast(has_review_comment as integer) as has_review_comment,
    product_category_name,
    product_category_name_english,
    cast(product_name_lenght as integer) as product_name_lenght,
    cast(product_description_lenght as integer) as product_description_lenght,
    cast(product_photos_qty as integer) as product_photos_qty,
    cast(product_weight_g as double) as product_weight_g,
    cast(product_length_cm as double) as product_length_cm,
    cast(product_height_cm as double) as product_height_cm,
    cast(product_width_cm as double) as product_width_cm,
    customer_zip_code_prefix,
    customer_city,
    customer_state,
    seller_zip_code_prefix,
    seller_city,
    seller_state,
    cast(seller_order_count as integer) as seller_order_count,
    cast(seller_avg_delivery_days as double) as seller_avg_delivery_days,
    cast(seller_delay_rate as double) as seller_delay_rate,
    seller_volume_tier,
    cast(latest_review_creation_date as timestamp) as latest_review_creation_date,
    cast(latest_review_answer_timestamp as timestamp) as latest_review_answer_timestamp
from read_parquet('{{ var("curated_analytics_path") }}/fact_orders_enriched.parquet')
