from __future__ import annotations

from pathlib import Path

import streamlit as st

from app.i18n import LOCALE_EN_US, Locale

_ARTIFACTS_PT_BR: dict[str, tuple[str, str]] = {
    "data_dictionary": (
        "Dicionário de Dados",
        "Documenta as colunas do ativo analítico e seus metadados estruturais.",
    ),
    "lgpd_controls": (
        "Controles LGPD",
        "Registra classificações de privacidade, risco e ações recomendadas "
        "produzidas pelo processo de governança.",
    ),
    "data_quality_report": (
        "Qualidade de Dados",
        "Registra checks de qualidade e seus resultados persistidos.",
    ),
    "lgpd_ripd_sample": (
        "RIPD Demonstrativo",
        "Apresenta uma avaliação demonstrativa de riscos e controles, sem "
        "substituir avaliação jurídica formal.",
    ),
}

_ARTIFACTS_EN_US: dict[str, tuple[str, str]] = {
    "data_dictionary": (
        "Data Dictionary",
        "Documents the analytical asset columns and their structural metadata.",
    ),
    "lgpd_controls": (
        "LGPD Controls",
        "Records privacy classifications, risk, and recommended actions produced "
        "by the governance process.",
    ),
    "data_quality_report": (
        "Data Quality",
        "Records data quality checks and their persisted results.",
    ),
    "lgpd_ripd_sample": (
        "Demonstrative RIPD",
        "Presents a demonstrative assessment of risks and controls without "
        "replacing a formal legal assessment.",
    ),
}


def _artifact_presentation(name: str, *, is_en: bool) -> tuple[str, str]:
    presentations = _ARTIFACTS_EN_US if is_en else _ARTIFACTS_PT_BR
    return presentations.get(name, (name, ""))


def render_governance_report(report_paths: dict[str, Path], locale: Locale) -> None:
    is_en = locale == LOCALE_EN_US
    st.title("Governance Evidence" if is_en else "Evidências de Governança")
    st.subheader(
        (
            "Persisted artifacts documenting data structure, privacy controls, "
            "quality, and demonstrative risk assessment."
        )
        if is_en
        else (
            "Artefatos persistidos que documentam estrutura dos dados, controles "
            "de privacidade, qualidade e avaliação demonstrativa de riscos."
        )
    )
    st.caption(
        (
            "These artifacts represent documents generated by the analytical "
            "process. Artifact availability does not imply automatic approval, "
            "legal compliance, or a publication decision."
        )
        if is_en
        else (
            "Estas evidências representam documentos gerados pelo processo "
            "analítico. Disponibilidade de um artefato não significa aprovação "
            "automática, conformidade jurídica ou decisão de publicação."
        )
    )
    st.markdown(
        "### How to interpret this page"
        if is_en
        else "### Como interpretar esta página"
    )
    st.write(
        (
            "Each artifact documents a different governance dimension. The "
            "displayed content is read directly from persisted artifacts and is "
            "not recalculated on this page."
        )
        if is_en
        else (
            "Cada evidência documenta uma dimensão diferente da governança. O "
            "conteúdo exibido é lido diretamente dos artefatos persistidos e não "
            "é recalculado nesta página."
        )
    )

    existing = {name: path for name, path in report_paths.items() if path.exists()}
    missing = {name: path for name, path in report_paths.items() if not path.exists()}

    if not existing and not missing:
        st.info(
            "No governance evidence has been configured for this context."
            if is_en
            else "Nenhuma evidência de governança foi configurada para este contexto."
        )
        return

    summary_tab, evidence_tab, technical_tab = st.tabs(
        ["Summary", "Evidence", "Technical details"]
        if is_en
        else ["Resumo", "Evidências", "Detalhes técnicos"]
    )
    contents: dict[str, str] = {}

    with summary_tab:
        expected_column, available_column, missing_column = st.columns(3)
        expected_column.metric(
            "Expected evidence" if is_en else "Evidências esperadas",
            str(len(report_paths)),
        )
        available_column.metric(
            "Available" if is_en else "Disponíveis",
            str(len(existing)),
        )
        missing_column.metric(
            "Missing" if is_en else "Ausentes",
            str(len(missing)),
        )

        st.markdown("### Executive summary" if is_en else "### Leitura executiva")
        if is_en:
            st.write(
                f"- {len(report_paths)} governance evidence artifacts are expected "
                "for the current asset."
            )
            st.write(
                f"- {len(existing)} artifacts are available in this environment."
            )
            st.write(
                "- No expected evidence is missing."
                if not missing
                else f"- {len(missing)} expected evidence artifacts are missing."
            )
            st.caption(
                "Availability means the artifact was persisted. Its content must "
                "be reviewed individually."
            )
            st.caption(
                "Classification, recommended action, and publication decision are "
                "distinct concepts. The documents on this page record evidence; "
                "they do not create a new publication decision."
            )
        else:
            st.write(
                f"- {len(report_paths)} evidências de governança são esperadas "
                "para o ativo atual."
            )
            st.write(
                f"- {len(existing)} artefatos estão disponíveis no ambiente."
            )
            st.write(
                "- Nenhuma evidência esperada está ausente."
                if not missing
                else f"- {len(missing)} evidências esperadas estão ausentes."
            )
            st.caption(
                "A disponibilidade indica que o artefato foi persistido. O "
                "conteúdo deve ser analisado individualmente."
            )
            st.caption(
                "Classificação, ação recomendada e decisão de publicação são "
                "conceitos distintos. Os documentos desta página registram "
                "evidências; eles não criam uma nova decisão de publicação."
            )

    with evidence_tab:
        for name, path in existing.items():
            friendly_name, description = _artifact_presentation(name, is_en=is_en)
            with st.expander(
                f":material/description: {friendly_name}", expanded=False
            ):
                if description:
                    st.caption(description)
                st.info(
                    "Available — the configured path exists."
                    if is_en
                    else "Disponível — o path configurado existe."
                )
                content = path.read_text(encoding="utf-8")
                contents[name] = content
                if content == "":
                    st.info(
                        "Persisted artifact with no textual content."
                        if is_en
                        else "Artefato persistido sem conteúdo textual."
                    )
                st.markdown(content)

        if missing:
            st.divider()
            st.markdown(
                "#### Evidence not persisted"
                if is_en
                else "#### Evidências não persistidas"
            )
            for name, _path in missing.items():
                friendly_name, description = _artifact_presentation(
                    name, is_en=is_en
                )
                with st.expander(
                    f":material/description: {friendly_name}", expanded=False
                ):
                    if description:
                        st.caption(description)
                    st.info("Not persisted" if is_en else "Não persistido")
                    st.write(
                        (
                            "The expected artifact was not found at the configured "
                            "path."
                        )
                        if is_en
                        else (
                            "O artefato esperado não foi encontrado no path "
                            "configurado."
                        )
                    )

    with technical_tab:
        st.caption(
            (
                "Technical identifiers, configured paths, and raw content are "
                "preserved below."
            )
            if is_en
            else (
                "Os identificadores técnicos, paths configurados e conteúdos "
                "brutos são preservados abaixo."
            )
        )
        for name, path in existing.items():
            friendly_name, _description = _artifact_presentation(name, is_en=is_en)
            with st.expander(
                f":material/code: {friendly_name} — `{name}`", expanded=False
            ):
                st.caption(
                    f"{'Internal identifier' if is_en else 'Identificador interno'}: "
                    f"`{name}`"
                )
                st.caption(f"{'Path' if is_en else 'Path real'}: `{path}`")
                st.code(contents[name], language="markdown")

        for name, path in missing.items():
            friendly_name, _description = _artifact_presentation(name, is_en=is_en)
            with st.expander(
                f":material/code: {friendly_name} — `{name}`", expanded=False
            ):
                st.info("Not persisted" if is_en else "Não persistido")
                st.caption(
                    f"{'Internal identifier' if is_en else 'Identificador interno'}: "
                    f"`{name}`"
                )
                st.caption(f"{'Path' if is_en else 'Path real'}: `{path}`")
