from __future__ import annotations

import streamlit as st

from pages._shared import (
    DATA_CLASSIFICATION_PATH,
    PIPELINE_LOG_PATH,
    PRIVACY_RISK_PATH,
    QUALITY_CHECKS_PATH,
    SCHEMA_CONTRACT_RESULTS_PATH,
    WORKFLOWS_DIR,
    count_statuses,
    format_datetime,
    read_csv_safe,
    read_json_safe,
    render_file_warning,
)

st.set_page_config(page_title="Overview | Governed Analytics", layout="wide")

st.title("Governed Analytics Platform")
st.caption(
    "Executive overview for governance, privacy, contracts, automation, and documentation."
)

st.markdown(
    """
    This page summarizes the current evidence generated by the governed analytics
    pipeline. It reads local artifacts when they exist and shows clear fallback
    messages when an artifact has not been generated yet.
    """
)

logs_df = read_csv_safe(PIPELINE_LOG_PATH)
quality_df = read_csv_safe(QUALITY_CHECKS_PATH)
classification_df = read_csv_safe(DATA_CLASSIFICATION_PATH)
contracts_df = read_csv_safe(SCHEMA_CONTRACT_RESULTS_PATH)
risk_payload = read_json_safe(PRIVACY_RISK_PATH)
workflows = sorted(WORKFLOWS_DIR.glob("*.json")) if WORKFLOWS_DIR.exists() else []

latest_status = "N/A"
latest_time = "No execution log found"
if not logs_df.empty:
    latest = logs_df.tail(1).iloc[0]
    latest_status = str(latest.get("status", "unknown")).upper()
    latest_time = format_datetime(latest.get("timestamp_utc", ""))

quality_counts = count_statuses(quality_df)
contract_counts = count_statuses(contracts_df)

col1, col2, col3, col4 = st.columns(4)
col1.metric("Pipeline status", latest_status)
col2.metric("Quality failures", quality_counts.get("FAIL", 0))
col3.metric("LGPD fields", len(classification_df) if not classification_df.empty else 0)
col4.metric("n8n workflows", len(workflows))

col5, col6, col7 = st.columns(3)
col5.metric("Privacy score", risk_payload.get("score", "N/A"))
col6.metric("Risk level", str(risk_payload.get("risk_level", "N/A")).upper())
col7.metric("Contract failures", contract_counts.get("FAIL", 0))

st.subheader("Last execution")
if logs_df.empty:
    render_file_warning(
        PIPELINE_LOG_PATH,
        "Run `scripts/register_pipeline_log.py` or the n8n workflow to populate it.",
    )
else:
    st.dataframe(
        logs_df.tail(5).sort_index(ascending=False), width="stretch", hide_index=True
    )
    st.caption(f"Most recent timestamp: {latest_time}")

st.subheader("Architecture in one view")
st.markdown(
    """
    - **Processing:** Python, SQL and DuckDB build and validate analytical assets.
    - **Governance:** quality checks, LGPD classification, privacy risk scoring,
      schema contracts and business rules are versioned in code.
    - **Orchestration:** n8n coordinates commands and alert placeholders, but does
      not own transformation logic.
    - **Presentation:** Streamlit reads generated artifacts and documentation for
      executive and technical review.
    """
)

st.subheader("Technology stack")
st.write(
    "Python, pandas, DuckDB, Streamlit, pytest, ruff, data contracts, LGPD controls, "
    "Markdown documentation, GitHub and n8n."
)
