from __future__ import annotations

import streamlit as st

from pages._shared import (
    DATA_CLASSIFICATION_PATH,
    PIPELINE_LOG_PATH,
    PRIVACY_RISK_PATH,
    PROJECT_ROOT,
    QUALITY_CHECKS_PATH,
    SCHEMA_CONTRACT_RESULTS_PATH,
    WORKFLOWS_DIR,
    count_statuses,
    format_datetime,
    read_csv_safe,
    read_json_safe,
    read_text_safe,
    relative_path,
    render_file_warning,
)

PUBLISHED_MONITORING_PATH = (
    PROJECT_ROOT / "data/published/monitoring/published_layer_monitoring.csv"
)
PUBLICATION_DECISION_PATH = (
    PROJECT_ROOT / "data/published/monitoring/publication_decision.json"
)
SCHEMA_CONTRACT_REPORT_PATH = PROJECT_ROOT / "docs/reports/schema_contract_report.md"


def _read_first_csv(paths):
    for path in paths:
        df = read_csv_safe(path)
        if not df.empty:
            return df, path
    return read_csv_safe(PROJECT_ROOT / "__missing__.csv"), None


def _read_first_json(paths):
    for path in paths:
        payload = read_json_safe(path)
        if payload:
            return payload, path
    return {}, None


def _read_schema_contract_results():
    df = read_csv_safe(SCHEMA_CONTRACT_RESULTS_PATH)
    if not df.empty:
        return df, SCHEMA_CONTRACT_RESULTS_PATH

    content = read_text_safe(SCHEMA_CONTRACT_REPORT_PATH)
    rows = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped.startswith("| `"):
            continue
        cells = [
            cell.strip().strip("`").strip("*")
            for cell in stripped.strip("|").split("|")
        ]
        if len(cells) < 4:
            continue
        dataset, check_name, status = cells[:3]
        rows.append(
            {
                "dataset_name": dataset,
                "check_name": check_name,
                "status": status,
                "details": " | ".join(cells[3:]),
            }
        )

    import pandas as pd

    return pd.DataFrame(rows), SCHEMA_CONTRACT_REPORT_PATH if rows else None

st.set_page_config(page_title="Overview | Governed Analytics", layout="wide")

st.title("Governed Analytics Platform")
st.caption(
    "Executive overview for governance, privacy, contracts, automation, and documentation."
)

st.markdown(
    """
    This page summarizes the current evidence generated by the governed analytics
    pipeline. It reads local artifacts when they exist and shows clear fallback
    messages when an artifact has not been generated yet.
    """
)

logs_df, _ = _read_first_csv([PIPELINE_LOG_PATH])
quality_df, quality_source = _read_first_csv([QUALITY_CHECKS_PATH, PUBLISHED_MONITORING_PATH])
classification_df, _ = _read_first_csv([DATA_CLASSIFICATION_PATH])
contracts_df, contracts_source = _read_schema_contract_results()
risk_payload, risk_source = _read_first_json([PRIVACY_RISK_PATH, PUBLICATION_DECISION_PATH])
workflows = sorted(WORKFLOWS_DIR.glob("*.json")) if WORKFLOWS_DIR.exists() else []

latest_status = "N/A"
latest_time = "No execution log found"
if not logs_df.empty:
    latest = logs_df.tail(1).iloc[0]
    latest_status = str(latest.get("status", "unknown")).upper()
    latest_time = format_datetime(latest.get("timestamp_utc", ""))
elif risk_payload:
    latest_status = str(risk_payload.get("status", "review")).upper()
    latest_time = format_datetime(risk_payload.get("timestamp_utc", ""))

quality_counts = count_statuses(quality_df)
contract_counts = count_statuses(contracts_df)

col1, col2, col3, col4 = st.columns(4)
col1.metric("Pipeline status", latest_status)
col2.metric("Quality failures", quality_counts.get("FAIL", 0))
col3.metric("LGPD fields", len(classification_df) if not classification_df.empty else 0)
col4.metric("n8n workflows", len(workflows))

col5, col6, col7 = st.columns(3)
privacy_score = risk_payload.get("score", risk_payload.get("privacy_risk_score", "N/A"))
risk_level = risk_payload.get("risk_level", risk_payload.get("status", "N/A"))
col5.metric("Privacy score", privacy_score)
col6.metric("Risk / publication status", str(risk_level).upper())
col7.metric("Contract failures", contract_counts.get("FAIL", 0))

source_notes = []
if quality_source:
    source_notes.append(f"Quality source: `{relative_path(quality_source)}`")
if risk_source:
    source_notes.append(f"Risk/status source: `{relative_path(risk_source)}`")
if contracts_source:
    source_notes.append(f"Contracts source: `{relative_path(contracts_source)}`")
if source_notes:
    st.caption(" | ".join(source_notes))

st.subheader("Last execution")
if logs_df.empty:
    if risk_payload:
        st.info(
            "Runtime pipeline logs were not found. The latest available "
            "publication decision is shown instead."
        )
        exec_col1, exec_col2, exec_col3 = st.columns(3)
        exec_col1.metric("Decision status", latest_status)
        exec_col2.metric("Dataset", risk_payload.get("dataset", "N/A"))
        exec_col3.metric(
            "Decision timestamp",
            latest_time or "N/A",
        )

        decision_reason = str(risk_payload.get("decision_reason", "")).strip()
        if decision_reason:
            st.warning(decision_reason)

        st.caption(
            f"Fallback source: `{relative_path(PUBLICATION_DECISION_PATH)}`. "
            "This is versioned governance evidence, not a fresh n8n execution log."
        )
    else:
        render_file_warning(
            PIPELINE_LOG_PATH,
            "Run `scripts/register_pipeline_log.py` or the n8n workflow to populate it.",
        )
else:
    st.dataframe(
        logs_df.tail(5).sort_index(ascending=False), width="stretch", hide_index=True
    )
    st.caption(f"Most recent timestamp: {latest_time}")

st.subheader("Architecture in one view")
st.markdown(
    """
    - **Processing:** Python, SQL and DuckDB build and validate analytical assets.
    - **Governance:** quality checks, LGPD classification, privacy risk scoring,
      schema contracts and business rules are versioned in code.
    - **Orchestration:** n8n coordinates commands and alert placeholders, but does
      not own transformation logic.
    - **Presentation:** Streamlit reads generated artifacts and documentation for
      executive and technical review.
    """
)

st.subheader("Technology stack")
st.write(
    "Python, pandas, DuckDB, Streamlit, pytest, ruff, data contracts, LGPD controls, "
    "Markdown documentation, GitHub and n8n."
)
