from __future__ import annotations

import pandas as pd
import streamlit as st

from pages._shared import (
    PUBLISHED_MONITORING_PATH,
    QUALITY_CHECKS_PATH,
    count_statuses,
    read_first_csv,
    relative_path,
    render_file_warning,
)

st.set_page_config(page_title="Data Quality | Governed Analytics", layout="wide")

st.title("Data Quality")
st.caption("Quality checks generated by the governed analytics pipeline.")

quality_df, quality_source = read_first_csv([QUALITY_CHECKS_PATH, PUBLISHED_MONITORING_PATH])

if quality_df.empty:
    render_file_warning(
        QUALITY_CHECKS_PATH,
        "Run `python scripts/run_data_quality.py` after the curated analytical dataset exists.",
    )
    st.stop()

if quality_source and quality_source != QUALITY_CHECKS_PATH:
    st.info(
        "The curated quality artifact was not found. Showing the versioned "
        f"published monitoring evidence from `{relative_path(quality_source)}`."
    )
elif quality_source:
    st.caption(f"Source: `{relative_path(quality_source)}`")

counts = count_statuses(quality_df)
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total checks", len(quality_df))
col2.metric("Success", counts.get("PASS", 0))
col3.metric("Warnings", counts.get("WARN", 0))
col4.metric("Errors", counts.get("FAIL", 0))

if "status" in quality_df.columns:
    status_chart = pd.DataFrame(
        [{"status": status, "count": count} for status, count in counts.items()]
    )
    st.bar_chart(status_chart.set_index("status"))

st.subheader("Quality check table")
st.dataframe(quality_df, width="stretch", hide_index=True)

if "status" in quality_df.columns:
    failed_df = quality_df[quality_df["status"].astype(str).str.upper() == "FAIL"]
    warn_df = quality_df[quality_df["status"].astype(str).str.upper() == "WARN"]
    if not failed_df.empty:
        st.error(
            "There are failing quality checks. Review the rows below before publication."
        )
        st.dataframe(failed_df, width="stretch", hide_index=True)
    elif not warn_df.empty:
        st.warning(
            "There are warnings. They are shown as residual issues, not execution failures."
        )
        st.dataframe(warn_df, width="stretch", hide_index=True)
    else:
        st.success("No failing or warning checks found in the latest quality artifact.")
