from __future__ import annotations

import pandas as pd
import streamlit as st

from streamlit_shared import (
    PROJECT_ROOT,
    QUALITY_CHECKS_PATH,
    count_statuses,
    read_csv_safe,
    relative_path,
    render_file_warning,
)

PUBLISHED_MONITORING_PATH = (
    PROJECT_ROOT / "data/published/monitoring/published_layer_monitoring.csv"
)


def _read_first_csv(paths):
    for path in paths:
        df = read_csv_safe(path)
        if not df.empty:
            return df, path
    return read_csv_safe(PROJECT_ROOT / "__missing__.csv"), None


st.set_page_config(page_title="Data Quality | Governed Analytics", layout="wide")

st.title("Data Quality")
st.caption("Quality and monitoring evidence generated by the governed analytics pipeline.")

quality_df, quality_source = _read_first_csv([QUALITY_CHECKS_PATH, PUBLISHED_MONITORING_PATH])
using_published_monitoring = quality_source == PUBLISHED_MONITORING_PATH

if quality_df.empty:
    render_file_warning(
        QUALITY_CHECKS_PATH,
        "Run `python scripts/run_data_quality.py` after the curated analytical dataset exists.",
    )
    st.stop()

if using_published_monitoring:
    st.info(
        "The curated quality report was not found in this environment. "
        "Showing versioned published-layer monitoring evidence instead."
    )
elif quality_source:
    st.caption(f"Source: `{relative_path(quality_source)}`")

counts = count_statuses(quality_df)
col1, col2, col3, col4 = st.columns(4)
col1.metric("Monitoring checks" if using_published_monitoring else "Total checks", len(quality_df))
col2.metric("Passed", counts.get("PASS", 0))
col3.metric("Warnings", counts.get("WARN", 0))
col4.metric("Errors", counts.get("FAIL", 0))

if "status" in quality_df.columns and len(counts) > 1:
    status_chart = pd.DataFrame(
        [{"status": status, "count": count} for status, count in counts.items()]
    )
    st.bar_chart(status_chart.set_index("status"))

st.subheader(
    "Published monitoring checks" if using_published_monitoring else "Quality check table"
)
if using_published_monitoring:
    st.caption(f"Source: `{relative_path(PUBLISHED_MONITORING_PATH)}`")
st.dataframe(quality_df, width="stretch", hide_index=True)

if "status" in quality_df.columns:
    failed_df = quality_df[quality_df["status"].astype(str).str.upper() == "FAIL"]
    warn_df = quality_df[quality_df["status"].astype(str).str.upper() == "WARN"]
    if not failed_df.empty:
        st.error(
            "There are failing quality checks. Review the rows below before publication."
        )
        st.dataframe(failed_df, width="stretch", hide_index=True)
    elif not warn_df.empty:
        st.warning(
            "There are warnings. They are shown as residual issues, not execution failures."
        )
        st.dataframe(warn_df, width="stretch", hide_index=True)
    else:
        if using_published_monitoring:
            st.success(
                "No failing or warning checks found in the versioned published-layer "
                "monitoring evidence."
            )
        else:
            st.success("No failing or warning checks found in the latest quality artifact.")
